---
  - name: Create keyrings directory
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
    become: yes

  - name: Download onlyoffice gpg key
    ansible.builtin.get_url:
      url: "{{ gpg_key_url }}"
      dest: "/etc/apt/keyrings/onlyoffice.asc"
      mode: '0644'
    become: yes

  - name: Add onlyoffice repositories
    ansible.builtin.apt_repository:
      repo: "{{ package_repo | replace('deb ', 'deb [signed-by=/etc/apt/keyrings/onlyoffice.asc] ') }}"
      state: present
    become: yes

  - name: Add debian contrib repositories
    ansible.builtin.apt_repository:
      repo: "{{ debian_repo }}"
      state: present
    when: ansible_distribution == "Debian"
    become: yes

  - name: Install desktopeditors
    ansible.builtin.apt: 
      name: "{{ package_name }}"
      update_cache: yes
      state: latest
    become: yes
